controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

_unlooped_grid:
    resource: '@UnloopedGridBundle/Resources/config/routing/filter.php'
    prefix: /grid
